In [1]:
import pandas as pd
import torch
import torch.nn as nn
import numpy

In [2]:
df = pd.read_csv("USStockMarket.csv")
df.head()

,Unnamed: 0,Date,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
0,0,2/2/2024,2.079,NaN,72.28,NaN,3.8215,NaN,"43,194.70",42650,...,"5,89,498",10580,564.64,4030000,171.81,117220000,474.99,84710000,"2,053.70",NaN
1,1,1/2/2024,2.050,161340.0,73.82,577940.0,3.8535,NaN,"43,081.40",47690,...,"5,81,600",9780,567.51,3150000,159.28,66360000,394.78,25140000,"2,071.10",260920.0
2,2,31-01-2024,2.100,142860.0,75.85,344490.0,3.9060,NaN,"42,580.50",56480,...,"5,78,020",9720,564.11,4830000,155.20,49690000,390.14,20010000,"2,067.40",238370.0
3,3,30-01-2024,2.077,139750.0,77.82,347240.0,3.9110,NaN,"42,946.20",55130,...,"5,84,680",9750,562.85,6120000,159.00,42290000,400.06,18610000,"2,050.90",214590.0
4,4,29-01-2024,2.490,3590.0,76.78,331930.0,3.8790,NaN,"43,299.80",45230,...,"5,78,800",13850,575.79,6880000,161.26,42840000,401.02,17790000,"2,034.90",1780.0

In [3]:
df.dropna(inplace=True)

In [4]:
df.tail()

,Unnamed: 0,Date,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
863,863,7/8/2020,2.238,206250.0,41.22,399000.0,2.8020,310.0,"11,592.00",517000,...,"3,14,334",440,494.73,5910000,158.37,78720000,268.44,72770000,"2,028.00",398130.0
864,864,6/8/2020,2.165,161990.0,41.95,359610.0,2.9190,290.0,"11,757.10",554850,...,"3,07,455",440,509.08,3730000,161.25,78810000,265.28,45240000,"2,069.40",312760.0
865,865,5/8/2020,2.191,182430.0,42.19,491270.0,2.9250,30.0,"11,735.10",570830,...,"3,05,200",560,502.11,4310000,160.25,78600000,249.12,13090000,"2,049.30",366380.0
866,866,4/8/2020,2.193,230890.0,41.70,451580.0,2.9030,50.0,"11,184.70",485790,...,"3,00,330",270,509.64,5610000,156.94,93890000,249.83,17180000,"2,021.00",274420.0
867,867,3/8/2020,2.101,381970.0,41.01,338330.0,2.9205,40.0,"11,224.40",470240,...,"2,98,800",470,498.62,5880000,155.59,101490000,251.96,23130000,"1,986.30",178750.0

In [5]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, format='mixed')
df.set_index('Date', inplace=True)

In [6]:
df.tail()

,Unnamed: 0,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,Platinum_Price,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
Date,,,,,,,,,,,,,,,,,,,,,
2020-08-07,863,2.238,206250.0,41.22,399000.0,2.8020,310.0,"11,592.00",517000,977.4,...,"3,14,334",440,494.73,5910000,158.37,78720000,268.44,72770000,"2,028.00",398130.0
2020-08-06,864,2.165,161990.0,41.95,359610.0,2.9190,290.0,"11,757.10",554850,"1,020.80",...,"3,07,455",440,509.08,3730000,161.25,78810000,265.28,45240000,"2,069.40",312760.0
2020-08-05,865,2.191,182430.0,42.19,491270.0,2.9250,30.0,"11,735.10",570830,994.9,...,"3,05,200",560,502.11,4310000,160.25,78600000,249.12,13090000,"2,049.30",366380.0
2020-08-04,866,2.193,230890.0,41.70,451580.0,2.9030,50.0,"11,184.70",485790,961,...,"3,00,330",270,509.64,5610000,156.94,93890000,249.83,17180000,"2,021.00",274420.0
2020-08-03,867,2.101,381970.0,41.01,338330.0,2.9205,40.0,"11,224.40",470240,938,...,"2,98,800",470,498.62,5880000,155.59,101490000,251.96,23130000,"1,986.30",178750.0

In [7]:
df_google = df["Google_Price"]
df_google = df_google.values

In [8]:
df_google[342]

143.61

In [9]:
def create_sequence(data, seq_lenth=30):
    x, y = [], []
    for i in range(len(data) - seq_lenth):
        x.append(data[i:i+seq_lenth])
        y.append(data[i+seq_lenth])
        return numpy.array(x) , numpy.array(y)

In [10]:
seq_lenth = 100
x, y = create_sequence(df_google, seq_lenth)

In [11]:
train_size = 0.8

x_train = x[:int(len(x) * train_size)]
y_train = y[:int(len(y) * train_size)]

y_test = y[int(len(y) * train_size):]
x_test = x[int(len(x) * train_size):]

In [12]:
x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.FloatTensor(y_train)
y_test = torch.FloatTensor(y_test)

In [37]:
type(x_train)

torch.Tensor

In [33]:
device

In [38]:
from zmq import device


class StockPriceLstm(nn.Module):
    def __init__(self, input_size, hidden_size=50, num_layer=2, output_size=1):
        super(StockPriceLstm, self).__init__()

        self.lstm = nn.LSTM(input_size, hidden_size, num_layer)
        self.linear = nn.Linear(hidden_size, output_size)
        self.num_layer = num_layer
        self.hidden_size = hidden_size

    def forward(self, x):
        h0 = torch.zeros(self.num_layer, x.shape[0], self.hidden_size).to(device, torch.FloatTensor)
        c0 = torch.zeros(self.num_layer, x.shape[0], self.hidden_size).to(device, torch.FloatTensor)

        out, _ = self.lstm(x, (h0, c0))
        out = self.linear(out[:, -1, :])

        return out

In [39]:
lstm_model = StockPriceLstm(seq_lenth)
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(lstm_model.parameters(), lr=0.01)

In [40]:
epochs = 1000
for epoch in range(epochs):
    y_pred = lstm_model(x_train)
    loss = loss_fn(y_pred, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch: {epoch}, Loss: {loss.item()}")

TypeError: to() received an invalid combination of arguments - got (_cython_3_0_0.cython_function_or_method, torch.tensortype), but expected one of:
 * (torch.device device, torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (torch.dtype dtype, bool non_blocking, bool copy, *, torch.memory_format memory_format)
 * (Tensor tensor, bool non_blocking, bool copy, *, torch.memory_format memory_format)