In [1]:
import pandas as pd
import torch
import torch.nn as nn
from sklearn.preprocessing import MinMaxScaler
from torch.utils.data import dataloader
import numpy

In [2]:
df = pd.read_csv("USStockMarket.csv")
df.head()

,Unnamed: 0,Date,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
0,0,2/2/2024,2.079,NaN,72.28,NaN,3.8215,NaN,"43,194.70",42650,...,"5,89,498",10580,564.64,4030000,171.81,117220000,474.99,84710000,"2,053.70",NaN
1,1,1/2/2024,2.050,161340.0,73.82,577940.0,3.8535,NaN,"43,081.40",47690,...,"5,81,600",9780,567.51,3150000,159.28,66360000,394.78,25140000,"2,071.10",260920.0
2,2,31-01-2024,2.100,142860.0,75.85,344490.0,3.9060,NaN,"42,580.50",56480,...,"5,78,020",9720,564.11,4830000,155.20,49690000,390.14,20010000,"2,067.40",238370.0
3,3,30-01-2024,2.077,139750.0,77.82,347240.0,3.9110,NaN,"42,946.20",55130,...,"5,84,680",9750,562.85,6120000,159.00,42290000,400.06,18610000,"2,050.90",214590.0
4,4,29-01-2024,2.490,3590.0,76.78,331930.0,3.8790,NaN,"43,299.80",45230,...,"5,78,800",13850,575.79,6880000,161.26,42840000,401.02,17790000,"2,034.90",1780.0

In [3]:
df.dropna(inplace=True)

In [4]:
df.tail()

,Unnamed: 0,Date,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
863,863,7/8/2020,2.238,206250.0,41.22,399000.0,2.8020,310.0,"11,592.00",517000,...,"3,14,334",440,494.73,5910000,158.37,78720000,268.44,72770000,"2,028.00",398130.0
864,864,6/8/2020,2.165,161990.0,41.95,359610.0,2.9190,290.0,"11,757.10",554850,...,"3,07,455",440,509.08,3730000,161.25,78810000,265.28,45240000,"2,069.40",312760.0
865,865,5/8/2020,2.191,182430.0,42.19,491270.0,2.9250,30.0,"11,735.10",570830,...,"3,05,200",560,502.11,4310000,160.25,78600000,249.12,13090000,"2,049.30",366380.0
866,866,4/8/2020,2.193,230890.0,41.70,451580.0,2.9030,50.0,"11,184.70",485790,...,"3,00,330",270,509.64,5610000,156.94,93890000,249.83,17180000,"2,021.00",274420.0
867,867,3/8/2020,2.101,381970.0,41.01,338330.0,2.9205,40.0,"11,224.40",470240,...,"2,98,800",470,498.62,5880000,155.59,101490000,251.96,23130000,"1,986.30",178750.0

In [5]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, format='mixed')
df.set_index('Date', inplace=True)

In [6]:
df.tail()

,Unnamed: 0,Natural_Gas_Price,Natural_Gas_Vol.,Crude_oil_Price,Crude_oil_Vol.,Copper_Price,Copper_Vol.,Bitcoin_Price,Bitcoin_Vol.,Platinum_Price,...,Berkshire_Price,Berkshire_Vol.,Netflix_Price,Netflix_Vol.,Amazon_Price,Amazon_Vol.,Meta_Price,Meta_Vol.,Gold_Price,Gold_Vol.
Date,,,,,,,,,,,,,,,,,,,,,
2020-08-07,863,2.238,206250.0,41.22,399000.0,2.8020,310.0,"11,592.00",517000,977.4,...,"3,14,334",440,494.73,5910000,158.37,78720000,268.44,72770000,"2,028.00",398130.0
2020-08-06,864,2.165,161990.0,41.95,359610.0,2.9190,290.0,"11,757.10",554850,"1,020.80",...,"3,07,455",440,509.08,3730000,161.25,78810000,265.28,45240000,"2,069.40",312760.0
2020-08-05,865,2.191,182430.0,42.19,491270.0,2.9250,30.0,"11,735.10",570830,994.9,...,"3,05,200",560,502.11,4310000,160.25,78600000,249.12,13090000,"2,049.30",366380.0
2020-08-04,866,2.193,230890.0,41.70,451580.0,2.9030,50.0,"11,184.70",485790,961,...,"3,00,330",270,509.64,5610000,156.94,93890000,249.83,17180000,"2,021.00",274420.0
2020-08-03,867,2.101,381970.0,41.01,338330.0,2.9205,40.0,"11,224.40",470240,938,...,"2,98,800",470,498.62,5880000,155.59,101490000,251.96,23130000,"1,986.30",178750.0

In [7]:
df_google = df["Google_Price"]
df_google = df_google.values

In [8]:
df_google[342]

143.61

In [9]:
stock_data = torch.FloatTensor(df_google).view(-1)

In [10]:
def create_sequence(data, seq_lenth=30):
    xs, ys = [], []
    for i in range(len(data) - seq_lenth):
        x = data[i:i+seq_lenth]
        y = data[i+seq_lenth]
        xs.append(x)
        ys.append(y)
    return torch.stack(xs), torch.stack(ys)

In [11]:
seq_lenth = 100
x, y = create_sequence(stock_data, seq_lenth)

In [12]:
x.shape, y.shape

(torch.Size([509, 100]), torch.Size([509]))

In [13]:
x, y

(tensor([[140.4200, 138.3400, 136.6500,  ..., 100.7700,  97.5600,  98.6400],
         [138.3400, 136.6500, 135.8000,  ...,  97.5600,  98.6400,  97.4200],
         [136.6500, 135.8000, 132.6000,  ...,  98.6400,  97.4200,  98.1700],
         ...,
         [ 86.1400,  87.0000,  86.3100,  ...,  74.8400,  74.9200,  75.2500],
         [ 87.0000,  86.3100,  87.6300,  ...,  74.9200,  75.2500,  73.9500],
         [ 86.3100,  87.6300,  86.8100,  ...,  75.2500,  73.9500,  73.6700]]),
 tensor([ 97.4200,  98.1700,  98.7400, 100.1400,  99.2800, 101.1400, 103.0700,
         102.8000, 102.9100, 105.0000, 104.3200, 110.8600, 110.6500, 109.4500,
         107.8500, 109.7400, 108.2200, 108.9400, 110.3400, 116.6500, 113.6900,
         113.8600, 114.2400, 117.2100, 120.1700, 119.5500, 121.7000, 122.0800,
         121.6800, 118.8400, 119.7000, 116.6300, 117.3000, 117.4700, 118.1900,
         118.0800, 115.1300, 114.8600, 116.3200, 114.2200, 113.0600, 105.0200,
         107.5100, 107.9000, 114.3400, 113.9000, 113.8100, 109.0300, 111.7800,
         110.3700, 111.3500, 114.0200, 115.6800, 118.7800, 114.5700, 108.7400,
         108.9600, 111.7000, 115.8300, 117.9700, 112.2400, 111.4900, 107.1400,
         106.0300, 109.7600, 106.7200, 106.3900, 111.1600, 114.8400, 117.1900,
         117.1500, 116.8200, 114.5400, 117.6200, 113.8900, 112.3200, 105.8100,
         105.9700, 111.4900, 108.9100, 110.3800, 111.9000, 116.4700, 114.4400,
         116.0500, 112.8400, 113.6000, 114.3900, 112.5100, 115.7500, 116.5100,
         122.2600, 117.3300, 116.5800, 114.1100, 118.5200, 118.6500, 123.0700,
         119.6400, 124.8100, 128.0400, 130.0100, 127.6800, 126.7300, 129.8900,
         127.7100, 128.8200, 133.2900, 135.8900, 136.5500, 140.5900, 142.9700,
         140.1500, 139.0700, 141.9400, 141.4600, 141.6700, 141.5700, 138.2800,
         139.8700, 136.1000, 136.1300, 133.8400, 133.2800, 129.2000, 125.9500,
         129.8700, 132.4300, 133.4200, 127.1000, 126.3800, 131.9100, 133.9000,
         134.5700, 134.0600, 135.0600, 134.4600, 127.5900, 130.4000, 132.5400,
         137.7400, 136.6100, 135.5300, 134.2800, 138.6200, 141.5900, 139.4000,
         139.2000, 143.2900, 143.0900, 148.0000, 137.6400, 135.3000, 133.3500,
         129.0100, 129.2300, 126.9300, 130.8000, 130.3500, 133.3100, 135.1200,
         139.4800, 138.5900, 141.4300, 139.7400, 138.6700, 137.0200, 137.7500,
         137.7700, 144.4000, 144.9900, 144.8500, 146.2000, 146.6900, 147.9100,
         146.9200, 146.4100, 143.4700, 141.6100, 141.7300, 144.4500, 146.4400,
         143.9100, 145.8300, 148.0000, 147.6400, 148.1900, 147.2700, 143.1500,
         142.0000, 142.9700, 141.0500, 141.9000, 145.5300, 146.1200, 145.7800,
         146.3000, 148.9300, 149.8400, 148.0500, 147.8800, 148.4500, 148.6800,
         145.7700, 145.8900, 148.9200, 149.0300, 148.8500, 148.2700, 146.6000,
         145.4300, 143.5000, 148.0500, 145.8500, 146.2200, 139.3100, 137.4500,
         137.5700, 141.8900, 141.7700, 143.2400, 142.7800, 141.3700, 141.1500,
         137.5800, 136.4500, 138.9100, 139.7900, 139.2300, 137.5700, 136.0200,
         133.6600, 136.5400, 133.6800, 134.3500, 141.0700, 142.2100, 141.2200,
         140.2800, 139.0300, 138.7200, 140.8000, 143.6100, 144.4300, 142.5400,
         142.3300, 140.8800, 143.5400, 143.6900, 143.7400, 143.2900, 145.2200,
         144.7000, 144.5900, 141.4400, 142.0800, 141.2600, 140.0400, 137.4300,
         135.6800, 135.4500, 136.6600, 138.3100, 137.7300, 137.1900, 136.2800,
         136.8100, 136.9100, 135.7400, 136.2500, 135.1300, 135.6300, 134.8500,
         134.7300, 135.7800, 136.0900, 131.9000, 134.0400, 133.0100, 128.4200,
         127.5500, 126.2100, 124.5800, 126.9700, 127.0000, 128.2400, 127.3400,
         126.9800, 125.5200, 125.0400, 126.4700, 125.2600, 122.4400, 122.0900,
         122.2700, 122.5100, 122.5000, 122.1300, 122.3300, 121.8100, 120.1100,
         121.7400, 120.7700, 121.4200, 122.4500, 121.5100, 121.7600, 120.4000,
         119.9200, 120.1100, 119.6800, 117.3800, 118.5300, 117.8400, 118.1300,
         118.1400, 118.0500, 114.7100, 115.3500, 113.5700, 113.1200, 114.4500,
         113.9200, 111.4500, 110.0100, 113.5000, 114.5900, 117.6000, 116.8700,
         115.7400, 115.3400, 117.1500, 117.6800, 119.6400, 117.9500, 114.5500,
         115.5000, 115.0000, 112.6300, 113.9200, 113.9500, 114.4900, 114.1400,
         114.2600, 112.1000, 112.7200, 112.2300, 113.5300, 112.5200, 111.9500,
         110.4600, 110.9500, 103.1300, 102.3200, 101.2400, 101.6200, 101.6300,
         102.0700, 101.5300, 101.3500, 101.0700, 104.1100, 104.1900, 102.7200,
         102.5000, 105.0300, 101.8100, 102.0200, 100.3800, 104.8500, 101.7000,
         100.5700, 103.2200, 103.4800, 101.1000, 100.8000, 103.0100, 102.7100,
         104.4400, 105.2900, 105.9300, 104.7500, 104.4400, 104.3200, 103.7700,
         104.2300, 104.4400, 102.6800, 102.9400,  95.9600,  94.6500,  91.3700,
          92.6600,  90.9500,  95.4000,  94.7100,  94.6300,  94.2100,  94.0000,
          86.3800,  86.5500,  87.3600,  86.8700,  87.8100,  89.8900,  88.7200,
          86.1400,  87.0000,  86.3100,  87.6300,  86.8100,  88.7000,  86.7100,
          86.4100,  86.0100,  86.7300,  86.3100,  87.0300,  87.8600,  88.0500,
          87.6100,  88.7400,  88.3800,  88.8900,  90.5700,  90.8500,  91.1900,
          91.0900,  91.2500,  89.7700,  87.7200,  88.1900,  86.3800,  86.8200,
          87.9300,  87.0300,  88.0800,  88.7000,  88.6100,  87.1400,  87.3600,
          86.8900,  88.0700,  87.9900,  88.1300,  87.2900,  82.2800,  81.2200,
          80.8100,  77.8400,  75.5400,  79.9400,  79.2100,  81.6500,  80.3300,
          79.3000,  77.5500,  76.5000,  78.3900,  77.7700,  78.1700,  78.3500,
          78.2300,  75.5200,  74.1700,  72.9600,  72.5500,  74.1400,  72.7800,
          74.3900,  73.2800,  73.3000,  71.9500,  71.1400,  70.4700,  72.9900,
          71.5100,  72.5500,  74.3500,  75.6000,  76.7600,  75.4400,  75.7900,
          76.3000,  77.3600,  79.0600,  81.4800,  85.8700,  82.7500,  81.4800,
          81.9700,  82.2100,  80.2900,  79.2600,  78.7800,  78.8100,  77.2300,
          77.7900,  75.8100,  75.2300,  75.8300,  75.3600,  74.0300,  74.8400,
          74.9200,  75.2500,  73.9500,  73.6700,  74.1400]))

In [14]:
train_size = int(len(y) * 0.8)

x_train = x[:train_size]
y_train = y[:train_size]

y_test = y[train_size:]
x_test = x[train_size:]

In [15]:
x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.FloatTensor(y_train)
y_test = torch.FloatTensor(y_test)

In [16]:
x_train.shape, y_train.shape

(torch.Size([407, 100]), torch.Size([407]))

In [17]:
x_train = x_train.unsqueeze(0)
y_train = y_train.unsqueeze(0)

In [18]:
x_train.reshape(1, -1)
y_train.reshape(1, -1)

tensor([[ 97.4200,  98.1700,  98.7400, 100.1400,  99.2800, 101.1400, 103.0700,
         102.8000, 102.9100, 105.0000, 104.3200, 110.8600, 110.6500, 109.4500,
         107.8500, 109.7400, 108.2200, 108.9400, 110.3400, 116.6500, 113.6900,
         113.8600, 114.2400, 117.2100, 120.1700, 119.5500, 121.7000, 122.0800,
         121.6800, 118.8400, 119.7000, 116.6300, 117.3000, 117.4700, 118.1900,
         118.0800, 115.1300, 114.8600, 116.3200, 114.2200, 113.0600, 105.0200,
         107.5100, 107.9000, 114.3400, 113.9000, 113.8100, 109.0300, 111.7800,
         110.3700, 111.3500, 114.0200, 115.6800, 118.7800, 114.5700, 108.7400,
         108.9600, 111.7000, 115.8300, 117.9700, 112.2400, 111.4900, 107.1400,
         106.0300, 109.7600, 106.7200, 106.3900, 111.1600, 114.8400, 117.1900,
         117.1500, 116.8200, 114.5400, 117.6200, 113.8900, 112.3200, 105.8100,
         105.9700, 111.4900, 108.9100, 110.3800, 111.9000, 116.4700, 114.4400,
         116.0500, 112.8400, 113.6000, 114.3900, 112.5100, 115.7500, 116.5100,
         122.2600, 117.3300, 116.5800, 114.1100, 118.5200, 118.6500, 123.0700,
         119.6400, 124.8100, 128.0400, 130.0100, 127.6800, 126.7300, 129.8900,
         127.7100, 128.8200, 133.2900, 135.8900, 136.5500, 140.5900, 142.9700,
         140.1500, 139.0700, 141.9400, 141.4600, 141.6700, 141.5700, 138.2800,
         139.8700, 136.1000, 136.1300, 133.8400, 133.2800, 129.2000, 125.9500,
         129.8700, 132.4300, 133.4200, 127.1000, 126.3800, 131.9100, 133.9000,
         134.5700, 134.0600, 135.0600, 134.4600, 127.5900, 130.4000, 132.5400,
         137.7400, 136.6100, 135.5300, 134.2800, 138.6200, 141.5900, 139.4000,
         139.2000, 143.2900, 143.0900, 148.0000, 137.6400, 135.3000, 133.3500,
         129.0100, 129.2300, 126.9300, 130.8000, 130.3500, 133.3100, 135.1200,
         139.4800, 138.5900, 141.4300, 139.7400, 138.6700, 137.0200, 137.7500,
         137.7700, 144.4000, 144.9900, 144.8500, 146.2000, 146.6900, 147.9100,
         146.9200, 146.4100, 143.4700, 141.6100, 141.7300, 144.4500, 146.4400,
         143.9100, 145.8300, 148.0000, 147.6400, 148.1900, 147.2700, 143.1500,
         142.0000, 142.9700, 141.0500, 141.9000, 145.5300, 146.1200, 145.7800,
         146.3000, 148.9300, 149.8400, 148.0500, 147.8800, 148.4500, 148.6800,
         145.7700, 145.8900, 148.9200, 149.0300, 148.8500, 148.2700, 146.6000,
         145.4300, 143.5000, 148.0500, 145.8500, 146.2200, 139.3100, 137.4500,
         137.5700, 141.8900, 141.7700, 143.2400, 142.7800, 141.3700, 141.1500,
         137.5800, 136.4500, 138.9100, 139.7900, 139.2300, 137.5700, 136.0200,
         133.6600, 136.5400, 133.6800, 134.3500, 141.0700, 142.2100, 141.2200,
         140.2800, 139.0300, 138.7200, 140.8000, 143.6100, 144.4300, 142.5400,
         142.3300, 140.8800, 143.5400, 143.6900, 143.7400, 143.2900, 145.2200,
         144.7000, 144.5900, 141.4400, 142.0800, 141.2600, 140.0400, 137.4300,
         135.6800, 135.4500, 136.6600, 138.3100, 137.7300, 137.1900, 136.2800,
         136.8100, 136.9100, 135.7400, 136.2500, 135.1300, 135.6300, 134.8500,
         134.7300, 135.7800, 136.0900, 131.9000, 134.0400, 133.0100, 128.4200,
         127.5500, 126.2100, 124.5800, 126.9700, 127.0000, 128.2400, 127.3400,
         126.9800, 125.5200, 125.0400, 126.4700, 125.2600, 122.4400, 122.0900,
         122.2700, 122.5100, 122.5000, 122.1300, 122.3300, 121.8100, 120.1100,
         121.7400, 120.7700, 121.4200, 122.4500, 121.5100, 121.7600, 120.4000,
         119.9200, 120.1100, 119.6800, 117.3800, 118.5300, 117.8400, 118.1300,
         118.1400, 118.0500, 114.7100, 115.3500, 113.5700, 113.1200, 114.4500,
         113.9200, 111.4500, 110.0100, 113.5000, 114.5900, 117.6000, 116.8700,
         115.7400, 115.3400, 117.1500, 117.6800, 119.6400, 117.9500, 114.5500,
         115.5000, 115.0000, 112.6300, 113.9200, 113.9500, 114.4900, 114.1400,
         114.2600, 112.1000, 112.7200, 112.2300, 113.5300, 112.5200, 111.9500,
         110.4600, 110.9500, 103.1300, 102.3200, 101.2400, 101.6200, 101.6300,
         102.0700, 101.5300, 101.3500, 101.0700, 104.1100, 104.1900, 102.7200,
         102.5000, 105.0300, 101.8100, 102.0200, 100.3800, 104.8500, 101.7000,
         100.5700, 103.2200, 103.4800, 101.1000, 100.8000, 103.0100, 102.7100,
         104.4400, 105.2900, 105.9300, 104.7500, 104.4400, 104.3200, 103.7700,
         104.2300, 104.4400, 102.6800, 102.9400,  95.9600,  94.6500,  91.3700,
          92.6600,  90.9500,  95.4000,  94.7100,  94.6300,  94.2100,  94.0000,
          86.3800,  86.5500,  87.3600,  86.8700,  87.8100,  89.8900,  88.7200,
          86.1400]])

In [19]:
x_train.shape, y_train.shape

(torch.Size([1, 407, 100]), torch.Size([1, 407]))

In [20]:
from zmq import device


class StockPriceLstm(nn.Module):
    def __init__(self, input_size=1, hidden_size=50, num_layer=1, output_size=1, batch_first=True):
        super(StockPriceLstm, self).__init__()

        self.lstm = nn.LSTM(input_size, hidden_size, num_layer, batch_first=batch_first)
        self.linear = nn.Linear(hidden_size, output_size)
        self.num_layer = num_layer
        self.hidden_size = hidden_size

    def forward(self, x):
        h0 = torch.zeros(self.num_layer, x.size(0), self.hidden_size).to(x.device)
        c0 = torch.zeros(self.num_layer, x.size(0), self.hidden_size).to(x.device)

        out, _ = self.lstm(x, (h0, c0))
        out = self.linear(out[:, -1, :])

        return out

In [21]:
lstm_model = StockPriceLstm(input_size=seq_lenth)
loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(lstm_model.parameters(), lr=0.01)

In [22]:
epochs = 2000
for epoch in range(epochs):
    for x_batch, y_batch in zip(x_train, y_train):
        y_pred = lstm_model(x_train)
        loss = loss_fn(y_pred, y_train)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 100 == 0:
            print(f"Epoch: {epoch}, Loss: {loss.item()}")

C:\Users\IMCK\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1, 407])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch: 0, Loss: 15667.4326171875
Epoch: 100, Loss: 12465.9921875
Epoch: 200, Loss: 9885.71484375
Epoch: 300, Loss: 7743.06005859375
Epoch: 400, Loss: 5986.83056640625
Epoch: 500, Loss: 4568.3125
Epoch: 600, Loss: 3441.15478515625
Epoch: 700, Loss: 2561.596923828125
Epoch: 800, Loss: 1888.837890625
Epoch: 900, Loss: 1385.4361572265625
Epoch: 1000, Loss: 1017.6907958984375
Epoch: 1100, Loss: 755.9595336914062
Epoch: 1200, Loss: 574.8526611328125
Epoch: 1300, Loss: 453.2630615234375
Epoch: 1400, Loss: 374.2242431640625
Epoch: 1500, Loss: 324.5726623535156
Epoch: 1600, Loss: 294.490234375
Epoch: 1700, Loss: 276.9443054199219
Epoch: 1800, Loss: 267.11041259765625
Epoch: 1900, Loss: 261.8247985839844